// Code generated by the experiment execution capability generator; DO NOT EDIT.
// Source SHA-256: 2f4b098fafda88f5052d4e0ac4461d5ec9520a671acde5be599fdda1d2fc360c

package execution

const generatedExecutionCapabilitiesJSON = `{
  "capability_version": "1.0.0",
  "classifications": [
    "executed",
    "conditional",
    "metadata_only",
    "unsupported"
  ],
  "field_catalog": {
    "augmentation": {
      "type": "object"
    },
    "augmentation.color_jitter": {
      "catalog_category": "augmentation_operations",
      "catalog_id": "color_jitter",
      "type": "boolean"
    },
    "augmentation.horizontal_flip": {
      "catalog_category": "augmentation_operations",
      "catalog_id": "horizontal_flip",
      "type": "boolean"
    },
    "augmentation.random_crop": {
      "catalog_category": "augmentation_operations",
      "catalog_id": "random_crop",
      "type": "boolean"
    },
    "augmentation.random_erasing": {
      "catalog_category": "augmentation_operations",
      "catalog_id": "random_erasing",
      "type": "boolean"
    },
    "augmentation.random_rotation": {
      "catalog_category": "augmentation_operations",
      "catalog_id": "random_rotation",
      "type": "boolean"
    },
    "augmentation.vertical_flip": {
      "catalog_category": "augmentation_operations",
      "catalog_id": "vertical_flip",
      "type": "boolean"
    },
    "augmentation_policy": {
      "aliases": {
        "auto_augment": "autoaugment",
        "rand_augment": "randaugment",
        "trivial_augment": "trivialaugment",
        "trivial_augment_wide": "trivialaugment",
        "trivialaugmentwide": "trivialaugment"
      },
      "catalog_category": "augmentation_policies",
      "normalization": "lowercase_trim",
      "type": "string",
      "values": [
        "none",
        "light",
        "moderate",
        "strong",
        "custom",
        "basic",
        "randaugment",
        "trivialaugment",
        "autoaugment",
        "mixup",
        "cutmix"
      ]
    },
    "augmentation_policy_config": {
      "type": "object"
    },
    "augmentation_policy_config.alpha": {
      "range": {
        "max": 1,
        "min": 0
      },
      "type": "number"
    },
    "augmentation_policy_config.magnitude": {
      "range": {
        "max": 15,
        "min": 0
      },
      "type": "integer"
    },
    "augmentation_policy_config.num_magnitude_bins": {
      "range": {
        "max": 31,
        "min": 2
      },
      "type": "integer"
    },
    "augmentation_policy_config.num_ops": {
      "range": {
        "max": 3,
        "min": 1
      },
      "type": "integer"
    },
    "augmentation_policy_config.policy_type": {
      "aliases": {
        "auto_augment": "autoaugment",
        "rand_augment": "randaugment",
        "trivial_augment": "trivialaugment",
        "trivial_augment_wide": "trivialaugment",
        "trivialaugmentwide": "trivialaugment"
      },
      "catalog_category": "augmentation_policies",
      "normalization": "lowercase_trim",
      "type": "string",
      "values": [
        "none",
        "basic",
        "randaugment",
        "trivialaugment",
        "autoaugment",
        "mixup",
        "cutmix"
      ]
    },
    "augmentation_policy_config.probability": {
      "range": {
        "max": 1,
        "min": 0
      },
      "type": "number"
    },
    "automl": {
      "type": "object"
    },
    "batch_size": {
      "range": {
        "max": 512,
        "min": 1
      },
      "required": true,
      "type": "integer"
    },
    "class_balancing": {
      "aliases": {
        "class_balanced_effective_number": "effective_number_loss",
        "class_weighted_loss": "weighted_loss",
        "effective_number": "effective_number_loss",
        "effective_number_class_balanced_loss": "effective_number_loss"
      },
      "catalog_category": "class_balancing_strategies",
      "normalization": "lowercase_trim",
      "type": "string",
      "values": [
        "none",
        "weighted_loss",
        "effective_number_loss",
        "class_balanced_sampler",
        "weighted_random_sampler",
        "focal_loss"
      ]
    },
    "class_balancing_config": {
      "type": "object"
    },
    "class_balancing_config.effective_number_beta": {
      "range": {
        "max": 0.99999,
        "min": 0.9
      },
      "type": "number"
    },
    "class_balancing_config.focal_loss_gamma": {
      "range": {
        "max": 5,
        "min": 0.5
      },
      "type": "number"
    },
    "dropout": {
      "range": {
        "max": 0.7,
        "min": 0
      },
      "type": "number"
    },
    "early_stopping_patience": {
      "range": {
        "max": 50,
        "min": 0
      },
      "type": "integer"
    },
    "epochs": {
      "range": {
        "max": 100,
        "min": 1
      },
      "required": true,
      "type": "integer"
    },
    "evidence_used": {
      "type": "string_array"
    },
    "expected_effect": {
      "normalization": "trim",
      "type": "string"
    },
    "fine_tune_strategy": {
      "catalog_category": "fine_tuning_modes",
      "normalization": "lowercase_trim",
      "type": "string",
      "values": [
        "head_only",
        "last_block",
        "full"
      ]
    },
    "freeze_backbone": {
      "type": "boolean"
    },
    "gradient_clip_norm": {
      "range": {
        "max": 10,
        "min": 0
      },
      "type": "number"
    },
    "image_size": {
      "range": {
        "max": 1280,
        "min": 0
      },
      "type": "integer"
    },
    "intervention": {
      "normalization": "trim",
      "type": "string"
    },
    "label_smoothing": {
      "range": {
        "max": 0.3,
        "min": 0
      },
      "type": "number"
    },
    "learning_rate": {
      "range": {
        "exclusive_min": 0,
        "max": 1
      },
      "required": true,
      "type": "number"
    },
    "mechanism": {
      "normalization": "lowercase_trim",
      "type": "string"
    },
    "model": {
      "catalog_category": "models",
      "normalization": "lowercase_trim",
      "required": true,
      "type": "string"
    },
    "optimizer": {
      "catalog_category": "optimizers",
      "normalization": "lowercase_trim",
      "type": "string",
      "values": [
        "adamw",
        "adam",
        "sgd"
      ]
    },
    "optimizer_momentum": {
      "range": {
        "max": 0.99,
        "min": 0
      },
      "type": "number"
    },
    "preprocessing": {
      "type": "object"
    },
    "preprocessing.bbox_mode": {
      "catalog_category": "bounding_box_modes",
      "normalization": "lowercase_trim",
      "type": "string",
      "values": [
        "ignore",
        "crop_if_available",
        "crop_and_compare_full_image",
        "use_boxes_as_metadata"
      ]
    },
    "preprocessing.crop_strategy": {
      "catalog_category": "crop_strategies",
      "normalization": "lowercase_trim",
      "type": "string",
      "values": [
        "none",
        "center_crop",
        "random_resized_crop",
        "bbox_crop_if_available",
        "bbox_crop_ablation"
      ]
    },
    "preprocessing.normalization": {
      "catalog_category": "normalization_strategies",
      "normalization": "lowercase_trim",
      "type": "string",
      "values": [
        "imagenet",
        "dataset",
        "none"
      ]
    },
    "preprocessing.resize_strategy": {
      "aliases": {
        "letterbox": "yolo_letterbox"
      },
      "catalog_category": "resize_strategies",
      "normalization": "lowercase_trim",
      "type": "string",
      "values": [
        "squash",
        "preserve_aspect_pad",
        "center_crop",
        "random_resized_crop",
        "bbox_crop_if_available",
        "yolo_letterbox"
      ]
    },
    "preprocessing.use_dataset_normalization": {
      "type": "boolean"
    },
    "pretrained": {
      "type": "boolean"
    },
    "reason": {
      "normalization": "trim",
      "type": "string"
    },
    "resolution_strategy": {
      "catalog_category": "resolution_strategies",
      "normalization": "lowercase_trim",
      "type": "string",
      "values": [
        "fixed",
        "low_latency",
        "compare_224_256",
        "high_resolution_ablation"
      ]
    },
    "sampling_strategy": {
      "catalog_category": "sampling_strategies",
      "normalization": "lowercase_trim",
      "type": "string",
      "values": [
        "none",
        "class_balanced_sampler",
        "weighted_random_sampler"
      ]
    },
    "scheduler": {
      "catalog_category": "schedulers",
      "normalization": "lowercase_trim",
      "type": "string",
      "values": [
        "none",
        "cosine",
        "step"
      ]
    },
    "scheduler_gamma": {
      "range": {
        "max": 0.95,
        "min": 0.05
      },
      "type": "number"
    },
    "scheduler_step_size": {
      "range": {
        "max": 100,
        "min": 1
      },
      "type": "integer"
    },
    "strategy": {
      "normalization": "lowercase_trim",
      "type": "string"
    },
    "template": {
      "normalization": "lowercase_trim",
      "required": true,
      "type": "string"
    },
    "weight_decay": {
      "range": {
        "max": 1,
        "min": 0
      },
      "type": "number"
    }
  },
  "profiles": {
    "image_classification.local_simulator": {
      "constraints": {
        "image_size": {
          "range": {
            "max": 1024,
            "min": 1
          }
        }
      },
      "default_expressions": {
        "scheduler_step_size": "max(1, floor(epochs / 3))"
      },
      "defaults": {
        "augmentation_policy": "none",
        "batch_size": 16,
        "class_balancing": "none",
        "dropout": 0,
        "early_stopping_patience": 0,
        "epochs": 3,
        "fine_tune_strategy": "head_only",
        "gradient_clip_norm": 0,
        "image_size": 224,
        "label_smoothing": 0,
        "learning_rate": 0.0003,
        "optimizer": "adamw",
        "optimizer_momentum": 0.9,
        "preprocessing.bbox_mode": "ignore",
        "preprocessing.crop_strategy": "none",
        "preprocessing.normalization": "imagenet",
        "preprocessing.resize_strategy": "squash",
        "preprocessing.use_dataset_normalization": false,
        "pretrained": true,
        "sampling_strategy": "none",
        "scheduler": "none",
        "scheduler_gamma": 0.5,
        "weight_decay": 0
      },
      "fields": {
        "augmentation": {
          "classification": "conditional",
          "reason_code": "simulator_scoring_input"
        },
        "augmentation.color_jitter": {
          "classification": "executed",
          "reason_code": "simulator_scoring_input"
        },
        "augmentation.horizontal_flip": {
          "classification": "executed",
          "reason_code": "simulator_scoring_input"
        },
        "augmentation.random_crop": {
          "classification": "executed",
          "reason_code": "simulator_scoring_input"
        },
        "augmentation.random_erasing": {
          "classification": "unsupported",
          "reason_code": "simulator_does_not_model"
        },
        "augmentation.random_rotation": {
          "classification": "unsupported",
          "reason_code": "simulator_does_not_model"
        },
        "augmentation.vertical_flip": {
          "classification": "executed",
          "reason_code": "simulator_scoring_input"
        },
        "augmentation_policy": {
          "classification": "executed",
          "reason_code": "simulator_scoring_input"
        },
        "augmentation_policy_config": {
          "classification": "conditional",
          "reason_code": "simulator_scoring_input"
        },
        "augmentation_policy_config.alpha": {
          "classification": "unsupported",
          "reason_code": "simulator_does_not_model"
        },
        "augmentation_policy_config.magnitude": {
          "classification": "unsupported",
          "reason_code": "simulator_does_not_model"
        },
        "augmentation_policy_config.num_magnitude_bins": {
          "classification": "unsupported",
          "reason_code": "simulator_does_not_model"
        },
        "augmentation_policy_config.num_ops": {
          "classification": "unsupported",
          "reason_code": "simulator_does_not_model"
        },
        "augmentation_policy_config.policy_type": {
          "classification": "executed",
          "reason_code": "simulator_scoring_input"
        },
        "augmentation_policy_config.probability": {
          "classification": "unsupported",
          "reason_code": "simulator_does_not_model"
        },
        "automl": {
          "classification": "metadata_only",
          "reason_code": "control_plane_only"
        },
        "batch_size": {
          "classification": "executed",
          "reason_code": "simulator_scoring_input"
        },
        "class_balancing": {
          "classification": "executed",
          "reason_code": "simulator_scoring_input"
        },
        "class_balancing_config": {
          "classification": "unsupported",
          "reason_code": "simulator_does_not_model"
        },
        "class_balancing_config.effective_number_beta": {
          "classification": "unsupported",
          "reason_code": "simulator_does_not_model"
        },
        "class_balancing_config.focal_loss_gamma": {
          "classification": "unsupported",
          "reason_code": "simulator_does_not_model"
        },
        "dropout": {
          "classification": "executed",
          "reason_code": "simulator_scoring_input"
        },
        "early_stopping_patience": {
          "classification": "unsupported",
          "reason_code": "simulator_does_not_model"
        },
        "epochs": {
          "classification": "executed",
          "reason_code": "simulator_scoring_input"
        },
        "evidence_used": {
          "classification": "metadata_only",
          "reason_code": "planner_provenance"
        },
        "expected_effect": {
          "classification": "metadata_only",
          "reason_code": "planner_provenance"
        },
        "fine_tune_strategy": {
          "classification": "unsupported",
          "reason_code": "simulator_does_not_model"
        },
        "freeze_backbone": {
          "classification": "unsupported",
          "reason_code": "simulator_does_not_model"
        },
        "gradient_clip_norm": {
          "classification": "executed",
          "reason_code": "simulator_scoring_input"
        },
        "image_size": {
          "classification": "executed",
          "reason_code": "simulator_scoring_input"
        },
        "intervention": {
          "classification": "metadata_only",
          "reason_code": "planner_provenance"
        },
        "label_smoothing": {
          "classification": "executed",
          "reason_code": "simulator_scoring_input"
        },
        "learning_rate": {
          "classification": "executed",
          "reason_code": "simulator_scoring_input"
        },
        "mechanism": {
          "classification": "metadata_only",
          "reason_code": "planner_provenance"
        },
        "model": {
          "classification": "executed",
          "reason_code": "simulator_scoring_input"
        },
        "optimizer": {
          "classification": "executed",
          "reason_code": "simulator_scoring_input"
        },
        "optimizer_momentum": {
          "classification": "conditional",
          "reason_code": "conditional_optimizer_sgd"
        },
        "preprocessing": {
          "classification": "conditional",
          "reason_code": "simulator_scoring_input"
        },
        "preprocessing.bbox_mode": {
          "classification": "unsupported",
          "reason_code": "simulator_does_not_model"
        },
        "preprocessing.crop_strategy": {
          "classification": "conditional",
          "reason_code": "simulator_scoring_input"
        },
        "preprocessing.normalization": {
          "classification": "conditional",
          "reason_code": "simulator_scoring_input"
        },
        "preprocessing.resize_strategy": {
          "classification": "conditional",
          "reason_code": "simulator_scoring_input"
        },
        "preprocessing.use_dataset_normalization": {
          "classification": "unsupported",
          "reason_code": "simulator_does_not_model"
        },
        "pretrained": {
          "classification": "unsupported",
          "reason_code": "simulator_does_not_model"
        },
        "reason": {
          "classification": "metadata_only",
          "reason_code": "planner_provenance"
        },
        "resolution_strategy": {
          "classification": "unsupported",
          "reason_code": "runner_does_not_consume"
        },
        "sampling_strategy": {
          "classification": "executed",
          "reason_code": "simulator_scoring_input"
        },
        "scheduler": {
          "classification": "executed",
          "reason_code": "simulator_scoring_input"
        },
        "scheduler_gamma": {
          "classification": "conditional",
          "reason_code": "conditional_scheduler_step"
        },
        "scheduler_step_size": {
          "classification": "conditional",
          "reason_code": "conditional_scheduler_step"
        },
        "strategy": {
          "classification": "metadata_only",
          "reason_code": "planner_provenance"
        },
        "template": {
          "classification": "metadata_only",
          "reason_code": "control_plane_only"
        },
        "weight_decay": {
          "classification": "executed",
          "reason_code": "simulator_scoring_input"
        }
      },
      "runner": "local_simulator",
      "task": "image_classification"
    },
    "image_classification.modal_torchvision": {
      "constraints": {
        "image_size": {
          "range": {
            "max": 384,
            "min": 96
          }
        },
        "preprocessing.resize_strategy": {
          "values": [
            "squash",
            "preserve_aspect_pad",
            "center_crop",
            "random_resized_crop",
            "bbox_crop_if_available"
          ]
        }
      },
      "default_expressions": {
        "scheduler_step_size": "max(1, floor(epochs / 3))"
      },
      "defaults": {
        "augmentation_policy": "none",
        "batch_size": 16,
        "class_balancing": "none",
        "dropout": 0,
        "early_stopping_patience": 0,
        "epochs": 5,
        "fine_tune_strategy": "head_only",
        "freeze_backbone": true,
        "gradient_clip_norm": 0,
        "image_size": 224,
        "label_smoothing": 0,
        "learning_rate": 0.0003,
        "optimizer": "adamw",
        "optimizer_momentum": 0.9,
        "preprocessing.bbox_mode": "ignore",
        "preprocessing.crop_strategy": "none",
        "preprocessing.normalization": "imagenet",
        "preprocessing.resize_strategy": "squash",
        "preprocessing.use_dataset_normalization": false,
        "pretrained": true,
        "sampling_strategy": "none",
        "scheduler": "none",
        "scheduler_gamma": 0.5,
        "weight_decay": 0
      },
      "fields": {
        "augmentation": {
          "classification": "conditional",
          "reason_code": "conditional_augmentation_policy"
        },
        "augmentation.color_jitter": {
          "classification": "conditional",
          "reason_code": "conditional_augmentation_policy"
        },
        "augmentation.horizontal_flip": {
          "classification": "conditional",
          "reason_code": "conditional_augmentation_policy"
        },
        "augmentation.random_crop": {
          "classification": "conditional",
          "reason_code": "conditional_augmentation_policy"
        },
        "augmentation.random_erasing": {
          "classification": "conditional",
          "reason_code": "conditional_augmentation_policy"
        },
        "augmentation.random_rotation": {
          "classification": "conditional",
          "reason_code": "conditional_augmentation_policy"
        },
        "augmentation.vertical_flip": {
          "classification": "conditional",
          "reason_code": "conditional_augmentation_policy"
        },
        "augmentation_policy": {
          "classification": "conditional",
          "reason_code": "conditional_augmentation_policy"
        },
        "augmentation_policy_config": {
          "classification": "conditional",
          "reason_code": "conditional_augmentation_policy"
        },
        "augmentation_policy_config.alpha": {
          "classification": "conditional",
          "reason_code": "conditional_augmentation_policy"
        },
        "augmentation_policy_config.magnitude": {
          "classification": "conditional",
          "reason_code": "conditional_augmentation_policy"
        },
        "augmentation_policy_config.num_magnitude_bins": {
          "classification": "conditional",
          "reason_code": "conditional_augmentation_policy"
        },
        "augmentation_policy_config.num_ops": {
          "classification": "conditional",
          "reason_code": "conditional_augmentation_policy"
        },
        "augmentation_policy_config.policy_type": {
          "classification": "conditional",
          "reason_code": "conditional_augmentation_policy"
        },
        "augmentation_policy_config.probability": {
          "classification": "conditional",
          "reason_code": "conditional_augmentation_policy"
        },
        "automl": {
          "classification": "metadata_only",
          "reason_code": "control_plane_only"
        },
        "batch_size": {
          "classification": "executed",
          "reason_code": "framework_argument"
        },
        "class_balancing": {
          "classification": "conditional",
          "reason_code": "conditional_class_balancing"
        },
        "class_balancing_config": {
          "classification": "conditional",
          "reason_code": "conditional_class_balancing"
        },
        "class_balancing_config.effective_number_beta": {
          "classification": "conditional",
          "reason_code": "conditional_class_balancing"
        },
        "class_balancing_config.focal_loss_gamma": {
          "classification": "conditional",
          "reason_code": "conditional_class_balancing"
        },
        "dropout": {
          "classification": "executed",
          "reason_code": "framework_argument"
        },
        "early_stopping_patience": {
          "classification": "conditional",
          "reason_code": "framework_argument"
        },
        "epochs": {
          "classification": "executed",
          "reason_code": "framework_argument"
        },
        "evidence_used": {
          "classification": "metadata_only",
          "reason_code": "planner_provenance"
        },
        "expected_effect": {
          "classification": "metadata_only",
          "reason_code": "planner_provenance"
        },
        "fine_tune_strategy": {
          "classification": "conditional",
          "reason_code": "conditional_transfer_learning"
        },
        "freeze_backbone": {
          "classification": "conditional",
          "reason_code": "conditional_transfer_learning"
        },
        "gradient_clip_norm": {
          "classification": "executed",
          "reason_code": "framework_argument"
        },
        "image_size": {
          "classification": "executed",
          "reason_code": "framework_argument"
        },
        "intervention": {
          "classification": "metadata_only",
          "reason_code": "planner_provenance"
        },
        "label_smoothing": {
          "classification": "executed",
          "reason_code": "framework_argument"
        },
        "learning_rate": {
          "classification": "executed",
          "reason_code": "framework_argument"
        },
        "mechanism": {
          "classification": "metadata_only",
          "reason_code": "planner_provenance"
        },
        "model": {
          "classification": "executed",
          "reason_code": "framework_argument"
        },
        "optimizer": {
          "classification": "executed",
          "reason_code": "framework_argument"
        },
        "optimizer_momentum": {
          "classification": "conditional",
          "reason_code": "conditional_optimizer_sgd"
        },
        "preprocessing": {
          "classification": "conditional",
          "reason_code": "conditional_preprocessing"
        },
        "preprocessing.bbox_mode": {
          "classification": "conditional",
          "reason_code": "conditional_preprocessing"
        },
        "preprocessing.crop_strategy": {
          "classification": "conditional",
          "reason_code": "conditional_preprocessing"
        },
        "preprocessing.normalization": {
          "classification": "conditional",
          "reason_code": "conditional_preprocessing"
        },
        "preprocessing.resize_strategy": {
          "classification": "conditional",
          "reason_code": "conditional_preprocessing"
        },
        "preprocessing.use_dataset_normalization": {
          "classification": "conditional",
          "reason_code": "conditional_preprocessing"
        },
        "pretrained": {
          "classification": "executed",
          "reason_code": "framework_argument"
        },
        "reason": {
          "classification": "metadata_only",
          "reason_code": "planner_provenance"
        },
        "resolution_strategy": {
          "classification": "unsupported",
          "reason_code": "runner_does_not_consume"
        },
        "sampling_strategy": {
          "classification": "conditional",
          "reason_code": "conditional_class_balancing"
        },
        "scheduler": {
          "classification": "executed",
          "reason_code": "framework_argument"
        },
        "scheduler_gamma": {
          "classification": "conditional",
          "reason_code": "conditional_scheduler_step"
        },
        "scheduler_step_size": {
          "classification": "conditional",
          "reason_code": "conditional_scheduler_step"
        },
        "strategy": {
          "classification": "metadata_only",
          "reason_code": "planner_provenance"
        },
        "template": {
          "classification": "metadata_only",
          "reason_code": "control_plane_only"
        },
        "weight_decay": {
          "classification": "executed",
          "reason_code": "framework_argument"
        }
      },
      "runner": "modal_torchvision",
      "task": "image_classification"
    },
    "object_detection.local_simulator": {
      "constraints": {
        "image_size": {
          "range": {
            "max": 1280,
            "min": 1
          }
        }
      },
      "defaults": {
        "batch_size": 8,
        "epochs": 5,
        "image_size": 640,
        "learning_rate": 0.001
      },
      "fields": {
        "augmentation": {
          "classification": "unsupported",
          "reason_code": "simulator_does_not_model"
        },
        "augmentation.color_jitter": {
          "classification": "unsupported",
          "reason_code": "simulator_does_not_model"
        },
        "augmentation.horizontal_flip": {
          "classification": "unsupported",
          "reason_code": "simulator_does_not_model"
        },
        "augmentation.random_crop": {
          "classification": "unsupported",
          "reason_code": "simulator_does_not_model"
        },
        "augmentation.random_erasing": {
          "classification": "unsupported",
          "reason_code": "simulator_does_not_model"
        },
        "augmentation.random_rotation": {
          "classification": "unsupported",
          "reason_code": "simulator_does_not_model"
        },
        "augmentation.vertical_flip": {
          "classification": "unsupported",
          "reason_code": "simulator_does_not_model"
        },
        "augmentation_policy": {
          "classification": "unsupported",
          "reason_code": "simulator_does_not_model"
        },
        "augmentation_policy_config": {
          "classification": "unsupported",
          "reason_code": "simulator_does_not_model"
        },
        "augmentation_policy_config.alpha": {
          "classification": "unsupported",
          "reason_code": "simulator_does_not_model"
        },
        "augmentation_policy_config.magnitude": {
          "classification": "unsupported",
          "reason_code": "simulator_does_not_model"
        },
        "augmentation_policy_config.num_magnitude_bins": {
          "classification": "unsupported",
          "reason_code": "simulator_does_not_model"
        },
        "augmentation_policy_config.num_ops": {
          "classification": "unsupported",
          "reason_code": "simulator_does_not_model"
        },
        "augmentation_policy_config.policy_type": {
          "classification": "unsupported",
          "reason_code": "simulator_does_not_model"
        },
        "augmentation_policy_config.probability": {
          "classification": "unsupported",
          "reason_code": "simulator_does_not_model"
        },
        "automl": {
          "classification": "metadata_only",
          "reason_code": "control_plane_only"
        },
        "batch_size": {
          "classification": "executed",
          "reason_code": "simulator_scoring_input"
        },
        "class_balancing": {
          "classification": "unsupported",
          "reason_code": "task_not_applicable"
        },
        "class_balancing_config": {
          "classification": "unsupported",
          "reason_code": "task_not_applicable"
        },
        "class_balancing_config.effective_number_beta": {
          "classification": "unsupported",
          "reason_code": "task_not_applicable"
        },
        "class_balancing_config.focal_loss_gamma": {
          "classification": "unsupported",
          "reason_code": "task_not_applicable"
        },
        "dropout": {
          "classification": "unsupported",
          "reason_code": "task_not_applicable"
        },
        "early_stopping_patience": {
          "classification": "unsupported",
          "reason_code": "simulator_does_not_model"
        },
        "epochs": {
          "classification": "executed",
          "reason_code": "simulator_scoring_input"
        },
        "evidence_used": {
          "classification": "metadata_only",
          "reason_code": "planner_provenance"
        },
        "expected_effect": {
          "classification": "metadata_only",
          "reason_code": "planner_provenance"
        },
        "fine_tune_strategy": {
          "classification": "unsupported",
          "reason_code": "task_not_applicable"
        },
        "freeze_backbone": {
          "classification": "unsupported",
          "reason_code": "task_not_applicable"
        },
        "gradient_clip_norm": {
          "classification": "unsupported",
          "reason_code": "simulator_does_not_model"
        },
        "image_size": {
          "classification": "executed",
          "reason_code": "simulator_scoring_input"
        },
        "intervention": {
          "classification": "metadata_only",
          "reason_code": "planner_provenance"
        },
        "label_smoothing": {
          "classification": "unsupported",
          "reason_code": "task_not_applicable"
        },
        "learning_rate": {
          "classification": "executed",
          "reason_code": "simulator_scoring_input"
        },
        "mechanism": {
          "classification": "metadata_only",
          "reason_code": "planner_provenance"
        },
        "model": {
          "classification": "executed",
          "reason_code": "simulator_scoring_input"
        },
        "optimizer": {
          "classification": "unsupported",
          "reason_code": "simulator_does_not_model"
        },
        "optimizer_momentum": {
          "classification": "unsupported",
          "reason_code": "simulator_does_not_model"
        },
        "preprocessing": {
          "classification": "unsupported",
          "reason_code": "framework_native_fixed"
        },
        "preprocessing.bbox_mode": {
          "classification": "unsupported",
          "reason_code": "task_not_applicable"
        },
        "preprocessing.crop_strategy": {
          "classification": "unsupported",
          "reason_code": "task_not_applicable"
        },
        "preprocessing.normalization": {
          "classification": "unsupported",
          "reason_code": "task_not_applicable"
        },
        "preprocessing.resize_strategy": {
          "classification": "unsupported",
          "reason_code": "framework_native_fixed"
        },
        "preprocessing.use_dataset_normalization": {
          "classification": "unsupported",
          "reason_code": "task_not_applicable"
        },
        "pretrained": {
          "classification": "unsupported",
          "reason_code": "framework_native_fixed"
        },
        "reason": {
          "classification": "metadata_only",
          "reason_code": "planner_provenance"
        },
        "resolution_strategy": {
          "classification": "unsupported",
          "reason_code": "runner_does_not_consume"
        },
        "sampling_strategy": {
          "classification": "unsupported",
          "reason_code": "task_not_applicable"
        },
        "scheduler": {
          "classification": "unsupported",
          "reason_code": "simulator_does_not_model"
        },
        "scheduler_gamma": {
          "classification": "unsupported",
          "reason_code": "simulator_does_not_model"
        },
        "scheduler_step_size": {
          "classification": "unsupported",
          "reason_code": "simulator_does_not_model"
        },
        "strategy": {
          "classification": "metadata_only",
          "reason_code": "planner_provenance"
        },
        "template": {
          "classification": "metadata_only",
          "reason_code": "control_plane_only"
        },
        "weight_decay": {
          "classification": "unsupported",
          "reason_code": "simulator_does_not_model"
        }
      },
      "fixed_semantics": {
        "pretrained": true
      },
      "runner": "local_simulator",
      "task": "object_detection"
    },
    "object_detection.modal_ultralytics": {
      "constraints": {
        "image_size": {
          "range": {
            "max": 1280,
            "min": 160
          }
        }
      },
      "defaults": {
        "batch_size": 8,
        "epochs": 8,
        "image_size": 640,
        "learning_rate": 0.001
      },
      "fields": {
        "augmentation": {
          "classification": "unsupported",
          "reason_code": "runner_does_not_consume"
        },
        "augmentation.color_jitter": {
          "classification": "unsupported",
          "reason_code": "task_not_applicable"
        },
        "augmentation.horizontal_flip": {
          "classification": "unsupported",
          "reason_code": "runner_does_not_consume"
        },
        "augmentation.random_crop": {
          "classification": "unsupported",
          "reason_code": "task_not_applicable"
        },
        "augmentation.random_erasing": {
          "classification": "unsupported",
          "reason_code": "task_not_applicable"
        },
        "augmentation.random_rotation": {
          "classification": "unsupported",
          "reason_code": "runner_does_not_consume"
        },
        "augmentation.vertical_flip": {
          "classification": "unsupported",
          "reason_code": "runner_does_not_consume"
        },
        "augmentation_policy": {
          "classification": "unsupported",
          "reason_code": "runner_does_not_consume"
        },
        "augmentation_policy_config": {
          "classification": "unsupported",
          "reason_code": "task_not_applicable"
        },
        "augmentation_policy_config.alpha": {
          "classification": "unsupported",
          "reason_code": "task_not_applicable"
        },
        "augmentation_policy_config.magnitude": {
          "classification": "unsupported",
          "reason_code": "task_not_applicable"
        },
        "augmentation_policy_config.num_magnitude_bins": {
          "classification": "unsupported",
          "reason_code": "task_not_applicable"
        },
        "augmentation_policy_config.num_ops": {
          "classification": "unsupported",
          "reason_code": "task_not_applicable"
        },
        "augmentation_policy_config.policy_type": {
          "classification": "unsupported",
          "reason_code": "task_not_applicable"
        },
        "augmentation_policy_config.probability": {
          "classification": "unsupported",
          "reason_code": "task_not_applicable"
        },
        "automl": {
          "classification": "metadata_only",
          "reason_code": "control_plane_only"
        },
        "batch_size": {
          "classification": "executed",
          "reason_code": "framework_argument"
        },
        "class_balancing": {
          "classification": "unsupported",
          "reason_code": "task_not_applicable"
        },
        "class_balancing_config": {
          "classification": "unsupported",
          "reason_code": "task_not_applicable"
        },
        "class_balancing_config.effective_number_beta": {
          "classification": "unsupported",
          "reason_code": "task_not_applicable"
        },
        "class_balancing_config.focal_loss_gamma": {
          "classification": "unsupported",
          "reason_code": "task_not_applicable"
        },
        "dropout": {
          "classification": "unsupported",
          "reason_code": "task_not_applicable"
        },
        "early_stopping_patience": {
          "classification": "unsupported",
          "reason_code": "runner_does_not_consume"
        },
        "epochs": {
          "classification": "executed",
          "reason_code": "framework_argument"
        },
        "evidence_used": {
          "classification": "metadata_only",
          "reason_code": "planner_provenance"
        },
        "expected_effect": {
          "classification": "metadata_only",
          "reason_code": "planner_provenance"
        },
        "fine_tune_strategy": {
          "classification": "unsupported",
          "reason_code": "task_not_applicable"
        },
        "freeze_backbone": {
          "classification": "unsupported",
          "reason_code": "task_not_applicable"
        },
        "gradient_clip_norm": {
          "classification": "unsupported",
          "reason_code": "runner_does_not_consume"
        },
        "image_size": {
          "classification": "executed",
          "reason_code": "framework_argument"
        },
        "intervention": {
          "classification": "metadata_only",
          "reason_code": "planner_provenance"
        },
        "label_smoothing": {
          "classification": "unsupported",
          "reason_code": "task_not_applicable"
        },
        "learning_rate": {
          "classification": "executed",
          "reason_code": "framework_argument"
        },
        "mechanism": {
          "classification": "metadata_only",
          "reason_code": "planner_provenance"
        },
        "model": {
          "classification": "executed",
          "reason_code": "framework_argument"
        },
        "optimizer": {
          "classification": "unsupported",
          "reason_code": "runner_does_not_consume"
        },
        "optimizer_momentum": {
          "classification": "unsupported",
          "reason_code": "runner_does_not_consume"
        },
        "preprocessing": {
          "classification": "unsupported",
          "reason_code": "framework_native_fixed"
        },
        "preprocessing.bbox_mode": {
          "classification": "unsupported",
          "reason_code": "task_not_applicable"
        },
        "preprocessing.crop_strategy": {
          "classification": "unsupported",
          "reason_code": "task_not_applicable"
        },
        "preprocessing.normalization": {
          "classification": "unsupported",
          "reason_code": "task_not_applicable"
        },
        "preprocessing.resize_strategy": {
          "classification": "unsupported",
          "reason_code": "framework_native_fixed"
        },
        "preprocessing.use_dataset_normalization": {
          "classification": "unsupported",
          "reason_code": "task_not_applicable"
        },
        "pretrained": {
          "classification": "unsupported",
          "reason_code": "framework_native_fixed"
        },
        "reason": {
          "classification": "metadata_only",
          "reason_code": "planner_provenance"
        },
        "resolution_strategy": {
          "classification": "unsupported",
          "reason_code": "runner_does_not_consume"
        },
        "sampling_strategy": {
          "classification": "unsupported",
          "reason_code": "task_not_applicable"
        },
        "scheduler": {
          "classification": "unsupported",
          "reason_code": "runner_does_not_consume"
        },
        "scheduler_gamma": {
          "classification": "unsupported",
          "reason_code": "runner_does_not_consume"
        },
        "scheduler_step_size": {
          "classification": "unsupported",
          "reason_code": "runner_does_not_consume"
        },
        "strategy": {
          "classification": "metadata_only",
          "reason_code": "planner_provenance"
        },
        "template": {
          "classification": "metadata_only",
          "reason_code": "control_plane_only"
        },
        "weight_decay": {
          "classification": "unsupported",
          "reason_code": "runner_does_not_consume"
        }
      },
      "fixed_semantics": {
        "preprocessing.resize_strategy": "yolo_letterbox",
        "pretrained": true
      },
      "runner": "modal_ultralytics",
      "task": "object_detection"
    }
  },
  "reason_codes": {
    "conditional_augmentation_policy": "The field is applied only when its augmentation policy or flag is active.",
    "conditional_class_balancing": "The field is applied only for the matching class-balancing or sampling strategy.",
    "conditional_optimizer_sgd": "The field is applied only when the optimizer is SGD.",
    "conditional_preprocessing": "The field is applied only when the requested preprocessing path and required metadata are available.",
    "conditional_scheduler_step": "The field is applied only when the scheduler is step.",
    "conditional_transfer_learning": "The field is applied only for the matching transfer-learning configuration.",
    "control_plane_only": "The field is consumed by orchestration or AutoML and is not a runner training semantic.",
    "framework_argument": "The value is forwarded to the selected training framework or custom training loop.",
    "framework_native_fixed": "The runner uses a fixed native framework behavior and does not consume this requested field.",
    "planner_provenance": "The field records planner intent or evidence and is not a training semantic.",
    "runner_does_not_consume": "The runner currently ignores this requested field.",
    "simulator_does_not_model": "The deterministic local simulator does not model this training semantic.",
    "simulator_scoring_input": "The value changes deterministic simulator scoring or progress.",
    "task_not_applicable": "The field has no equivalent semantic for this task."
  },
  "runners": {
    "local_simulator": {
      "providers": [
        "local",
        "persistent_gpu",
        "persistent_disk"
      ],
      "simulated": true
    },
    "modal_torchvision": {
      "model_kind": "torchvision_classifier",
      "providers": [
        "modal"
      ],
      "simulated": false
    },
    "modal_ultralytics": {
      "model_kind": "ultralytics_yolo_detector",
      "providers": [
        "modal"
      ],
      "simulated": false
    }
  },
  "schema_version": "experiment_execution_capabilities.v1",
  "tasks": {
    "image_classification": {
      "runners": {
        "local_simulator": {
          "profile": "image_classification.local_simulator"
        },
        "modal_torchvision": {
          "profile": "image_classification.modal_torchvision"
        }
      }
    },
    "object_detection": {
      "runners": {
        "local_simulator": {
          "profile": "object_detection.local_simulator"
        },
        "modal_ultralytics": {
          "profile": "object_detection.modal_ultralytics"
        }
      }
    }
  }
}
`
