# Code generated by generate_model_express_catalog.py; DO NOT EDIT.
# Source SHA-256: a3acdda4c20e614abd26f9a942a093728392560a60f62f89bdf98192212d66f9

from __future__ import annotations

import json


CATALOG_DOCUMENT = json.loads(r'''{
  "catalog_version": "1.0.0",
  "categories": {
    "augmentation_operations": [
      {
        "aliases": [],
        "attributes": {},
        "available": true,
        "equivalent_to": [],
        "id": "horizontal_flip",
        "implies": [],
        "runners": [
          "local_simulator",
          "modal_torchvision"
        ],
        "tasks": [
          "image_classification"
        ]
      },
      {
        "aliases": [],
        "attributes": {},
        "available": true,
        "equivalent_to": [],
        "id": "vertical_flip",
        "implies": [],
        "runners": [
          "local_simulator",
          "modal_torchvision"
        ],
        "tasks": [
          "image_classification"
        ]
      },
      {
        "aliases": [],
        "attributes": {},
        "available": true,
        "equivalent_to": [],
        "id": "color_jitter",
        "implies": [],
        "runners": [
          "local_simulator",
          "modal_torchvision"
        ],
        "tasks": [
          "image_classification"
        ]
      },
      {
        "aliases": [],
        "attributes": {},
        "available": true,
        "equivalent_to": [],
        "id": "random_crop",
        "implies": [],
        "runners": [
          "local_simulator",
          "modal_torchvision"
        ],
        "tasks": [
          "image_classification"
        ]
      },
      {
        "aliases": [],
        "attributes": {},
        "available": true,
        "equivalent_to": [],
        "id": "random_rotation",
        "implies": [],
        "runners": [
          "modal_torchvision"
        ],
        "tasks": [
          "image_classification"
        ]
      },
      {
        "aliases": [],
        "attributes": {},
        "available": true,
        "equivalent_to": [],
        "id": "random_erasing",
        "implies": [],
        "runners": [
          "modal_torchvision"
        ],
        "tasks": [
          "image_classification"
        ]
      }
    ],
    "augmentation_policies": [
      {
        "aliases": [],
        "attributes": {
          "structured": true
        },
        "available": true,
        "equivalent_to": [],
        "id": "none",
        "implies": [],
        "runners": [
          "local_simulator",
          "modal_torchvision"
        ],
        "tasks": [
          "image_classification"
        ]
      },
      {
        "aliases": [],
        "attributes": {
          "structured": false
        },
        "available": true,
        "equivalent_to": [],
        "id": "light",
        "implies": [
          "augmentation_operations/horizontal_flip"
        ],
        "runners": [
          "local_simulator",
          "modal_torchvision"
        ],
        "tasks": [
          "image_classification"
        ]
      },
      {
        "aliases": [],
        "attributes": {
          "structured": false
        },
        "available": true,
        "equivalent_to": [],
        "id": "moderate",
        "implies": [
          "augmentation_operations/horizontal_flip",
          "augmentation_operations/color_jitter",
          "augmentation_operations/random_crop"
        ],
        "runners": [
          "local_simulator",
          "modal_torchvision"
        ],
        "tasks": [
          "image_classification"
        ]
      },
      {
        "aliases": [],
        "attributes": {
          "structured": false
        },
        "available": true,
        "equivalent_to": [],
        "id": "strong",
        "implies": [
          "augmentation_operations/horizontal_flip",
          "augmentation_operations/color_jitter",
          "augmentation_operations/random_crop",
          "augmentation_operations/random_rotation",
          "augmentation_operations/random_erasing"
        ],
        "runners": [
          "local_simulator",
          "modal_torchvision"
        ],
        "tasks": [
          "image_classification"
        ]
      },
      {
        "aliases": [],
        "attributes": {
          "structured": false
        },
        "available": true,
        "equivalent_to": [],
        "id": "custom",
        "implies": [],
        "runners": [
          "local_simulator",
          "modal_torchvision"
        ],
        "tasks": [
          "image_classification"
        ]
      },
      {
        "aliases": [],
        "attributes": {
          "structured": true
        },
        "available": true,
        "equivalent_to": [],
        "id": "basic",
        "implies": [
          "augmentation_operations/horizontal_flip"
        ],
        "runners": [
          "local_simulator",
          "modal_torchvision"
        ],
        "tasks": [
          "image_classification"
        ]
      },
      {
        "aliases": [
          "rand_augment"
        ],
        "attributes": {
          "structured": true
        },
        "available": true,
        "equivalent_to": [],
        "id": "randaugment",
        "implies": [],
        "runners": [
          "modal_torchvision"
        ],
        "tasks": [
          "image_classification"
        ]
      },
      {
        "aliases": [
          "trivial_augment",
          "trivial_augment_wide",
          "trivialaugmentwide"
        ],
        "attributes": {
          "structured": true
        },
        "available": true,
        "equivalent_to": [],
        "id": "trivialaugment",
        "implies": [],
        "runners": [
          "modal_torchvision"
        ],
        "tasks": [
          "image_classification"
        ]
      },
      {
        "aliases": [
          "auto_augment"
        ],
        "attributes": {
          "structured": true
        },
        "available": true,
        "equivalent_to": [],
        "id": "autoaugment",
        "implies": [],
        "runners": [
          "modal_torchvision"
        ],
        "tasks": [
          "image_classification"
        ]
      },
      {
        "aliases": [],
        "attributes": {
          "structured": true
        },
        "available": true,
        "equivalent_to": [],
        "id": "mixup",
        "implies": [],
        "runners": [
          "modal_torchvision"
        ],
        "tasks": [
          "image_classification"
        ]
      },
      {
        "aliases": [],
        "attributes": {
          "structured": true
        },
        "available": true,
        "equivalent_to": [],
        "id": "cutmix",
        "implies": [],
        "runners": [
          "modal_torchvision"
        ],
        "tasks": [
          "image_classification"
        ]
      }
    ],
    "bounding_box_modes": [
      {
        "aliases": [],
        "attributes": {},
        "available": true,
        "equivalent_to": [],
        "id": "ignore",
        "implies": [],
        "runners": [
          "local_simulator",
          "modal_torchvision"
        ],
        "tasks": [
          "image_classification"
        ]
      },
      {
        "aliases": [],
        "attributes": {},
        "available": true,
        "equivalent_to": [],
        "id": "crop_if_available",
        "implies": [],
        "runners": [
          "modal_torchvision"
        ],
        "tasks": [
          "image_classification"
        ]
      },
      {
        "aliases": [],
        "attributes": {},
        "available": true,
        "equivalent_to": [],
        "id": "crop_and_compare_full_image",
        "implies": [],
        "runners": [
          "modal_torchvision"
        ],
        "tasks": [
          "image_classification"
        ]
      },
      {
        "aliases": [],
        "attributes": {},
        "available": true,
        "equivalent_to": [],
        "id": "use_boxes_as_metadata",
        "implies": [],
        "runners": [
          "modal_torchvision"
        ],
        "tasks": [
          "image_classification"
        ]
      }
    ],
    "class_balancing_strategies": [
      {
        "aliases": [],
        "attributes": {},
        "available": true,
        "equivalent_to": [],
        "id": "none",
        "implies": [],
        "runners": [
          "local_simulator",
          "modal_torchvision"
        ],
        "tasks": [
          "image_classification"
        ]
      },
      {
        "aliases": [
          "class_weighted_loss"
        ],
        "attributes": {},
        "available": true,
        "equivalent_to": [],
        "id": "weighted_loss",
        "implies": [],
        "runners": [
          "local_simulator",
          "modal_torchvision"
        ],
        "tasks": [
          "image_classification"
        ]
      },
      {
        "aliases": [
          "class_balanced_effective_number",
          "effective_number",
          "effective_number_class_balanced_loss"
        ],
        "attributes": {},
        "available": true,
        "equivalent_to": [],
        "id": "effective_number_loss",
        "implies": [],
        "runners": [
          "local_simulator",
          "modal_torchvision"
        ],
        "tasks": [
          "image_classification"
        ]
      },
      {
        "aliases": [],
        "attributes": {},
        "available": true,
        "equivalent_to": [],
        "id": "class_balanced_sampler",
        "implies": [],
        "runners": [
          "local_simulator",
          "modal_torchvision"
        ],
        "tasks": [
          "image_classification"
        ]
      },
      {
        "aliases": [],
        "attributes": {},
        "available": true,
        "equivalent_to": [],
        "id": "weighted_random_sampler",
        "implies": [],
        "runners": [
          "local_simulator",
          "modal_torchvision"
        ],
        "tasks": [
          "image_classification"
        ]
      },
      {
        "aliases": [],
        "attributes": {},
        "available": true,
        "equivalent_to": [],
        "id": "focal_loss",
        "implies": [],
        "runners": [
          "local_simulator",
          "modal_torchvision"
        ],
        "tasks": [
          "image_classification"
        ]
      }
    ],
    "crop_strategies": [
      {
        "aliases": [],
        "attributes": {},
        "available": true,
        "equivalent_to": [],
        "id": "none",
        "implies": [],
        "runners": [
          "local_simulator",
          "modal_torchvision"
        ],
        "tasks": [
          "image_classification"
        ]
      },
      {
        "aliases": [],
        "attributes": {},
        "available": true,
        "equivalent_to": [],
        "id": "center_crop",
        "implies": [],
        "runners": [
          "local_simulator",
          "modal_torchvision"
        ],
        "tasks": [
          "image_classification"
        ]
      },
      {
        "aliases": [],
        "attributes": {},
        "available": true,
        "equivalent_to": [],
        "id": "random_resized_crop",
        "implies": [],
        "runners": [
          "local_simulator",
          "modal_torchvision"
        ],
        "tasks": [
          "image_classification"
        ]
      },
      {
        "aliases": [],
        "attributes": {},
        "available": true,
        "equivalent_to": [],
        "id": "bbox_crop_if_available",
        "implies": [],
        "runners": [
          "modal_torchvision"
        ],
        "tasks": [
          "image_classification"
        ]
      },
      {
        "aliases": [],
        "attributes": {},
        "available": true,
        "equivalent_to": [],
        "id": "bbox_crop_ablation",
        "implies": [],
        "runners": [
          "modal_torchvision"
        ],
        "tasks": [
          "image_classification"
        ]
      }
    ],
    "deployment_tiers": [
      {
        "aliases": [],
        "attributes": {},
        "available": true,
        "equivalent_to": [],
        "id": "fast_live",
        "implies": [],
        "runners": [
          "local_simulator",
          "modal_torchvision"
        ],
        "tasks": [
          "image_classification"
        ]
      },
      {
        "aliases": [],
        "attributes": {},
        "available": true,
        "equivalent_to": [],
        "id": "balanced",
        "implies": [],
        "runners": [
          "local_simulator",
          "modal_torchvision"
        ],
        "tasks": [
          "image_classification"
        ]
      },
      {
        "aliases": [],
        "attributes": {},
        "available": true,
        "equivalent_to": [],
        "id": "quality_challenger",
        "implies": [],
        "runners": [
          "local_simulator",
          "modal_torchvision"
        ],
        "tasks": [
          "image_classification"
        ]
      },
      {
        "aliases": [],
        "attributes": {},
        "available": true,
        "equivalent_to": [],
        "id": "realtime_detector",
        "implies": [],
        "runners": [
          "local_simulator",
          "modal_ultralytics"
        ],
        "tasks": [
          "object_detection"
        ]
      },
      {
        "aliases": [],
        "attributes": {},
        "available": true,
        "equivalent_to": [],
        "id": "quality_detector",
        "implies": [],
        "runners": [
          "local_simulator",
          "modal_ultralytics"
        ],
        "tasks": [
          "object_detection"
        ]
      }
    ],
    "execution_providers": [
      {
        "aliases": [
          "CPUExecutionProvider"
        ],
        "attributes": {},
        "available": true,
        "equivalent_to": [],
        "id": "cpu_execution_provider",
        "implies": [],
        "runners": [
          "modal_torchvision",
          "modal_ultralytics"
        ],
        "tasks": [
          "image_classification",
          "object_detection"
        ]
      }
    ],
    "execution_requirements": [
      {
        "aliases": [],
        "attributes": {},
        "available": true,
        "equivalent_to": [],
        "id": "cpu_compatible",
        "implies": [],
        "runners": [
          "modal_torchvision",
          "modal_ultralytics"
        ],
        "tasks": [
          "image_classification",
          "object_detection"
        ]
      },
      {
        "aliases": [],
        "attributes": {},
        "available": false,
        "equivalent_to": [],
        "id": "cuda_required",
        "implies": [],
        "runners": [],
        "tasks": []
      }
    ],
    "export_formats": [
      {
        "aliases": [],
        "attributes": {},
        "available": true,
        "equivalent_to": [],
        "id": "onnx",
        "implies": [],
        "runners": [
          "modal_torchvision",
          "modal_ultralytics"
        ],
        "tasks": [
          "image_classification",
          "object_detection"
        ]
      },
      {
        "aliases": [],
        "attributes": {},
        "available": true,
        "equivalent_to": [],
        "id": "torchscript",
        "implies": [],
        "runners": [
          "modal_torchvision"
        ],
        "tasks": [
          "image_classification"
        ]
      },
      {
        "aliases": [],
        "attributes": {},
        "available": true,
        "equivalent_to": [],
        "id": "pytorch",
        "implies": [],
        "runners": [
          "modal_torchvision",
          "modal_ultralytics"
        ],
        "tasks": [
          "image_classification",
          "object_detection"
        ]
      },
      {
        "aliases": [],
        "attributes": {},
        "available": true,
        "equivalent_to": [],
        "id": "safetensors",
        "implies": [],
        "runners": [
          "modal_torchvision"
        ],
        "tasks": [
          "image_classification"
        ]
      }
    ],
    "fine_tuning_modes": [
      {
        "aliases": [],
        "attributes": {},
        "available": true,
        "equivalent_to": [],
        "id": "head_only",
        "implies": [],
        "runners": [
          "modal_torchvision"
        ],
        "tasks": [
          "image_classification"
        ]
      },
      {
        "aliases": [],
        "attributes": {},
        "available": true,
        "equivalent_to": [],
        "id": "last_block",
        "implies": [],
        "runners": [
          "modal_torchvision"
        ],
        "tasks": [
          "image_classification"
        ]
      },
      {
        "aliases": [],
        "attributes": {},
        "available": true,
        "equivalent_to": [],
        "id": "full",
        "implies": [],
        "runners": [
          "modal_torchvision"
        ],
        "tasks": [
          "image_classification"
        ]
      }
    ],
    "latency_tiers": [
      {
        "aliases": [],
        "attributes": {},
        "available": true,
        "equivalent_to": [],
        "id": "very_fast",
        "implies": [],
        "runners": [],
        "tasks": []
      },
      {
        "aliases": [],
        "attributes": {},
        "available": true,
        "equivalent_to": [],
        "id": "fast",
        "implies": [],
        "runners": [],
        "tasks": []
      },
      {
        "aliases": [],
        "attributes": {},
        "available": true,
        "equivalent_to": [],
        "id": "medium",
        "implies": [],
        "runners": [],
        "tasks": []
      },
      {
        "aliases": [],
        "attributes": {},
        "available": true,
        "equivalent_to": [],
        "id": "medium_slow",
        "implies": [],
        "runners": [],
        "tasks": []
      },
      {
        "aliases": [],
        "attributes": {},
        "available": true,
        "equivalent_to": [],
        "id": "slow",
        "implies": [],
        "runners": [],
        "tasks": []
      },
      {
        "aliases": [],
        "attributes": {},
        "available": true,
        "equivalent_to": [],
        "id": "slowest",
        "implies": [],
        "runners": [],
        "tasks": []
      }
    ],
    "model_families": [
      {
        "aliases": [],
        "attributes": {},
        "available": true,
        "equivalent_to": [],
        "id": "mobilenet",
        "implies": [],
        "runners": [
          "local_simulator",
          "modal_torchvision"
        ],
        "tasks": [
          "image_classification"
        ]
      },
      {
        "aliases": [],
        "attributes": {},
        "available": true,
        "equivalent_to": [],
        "id": "efficientnet",
        "implies": [],
        "runners": [
          "local_simulator",
          "modal_torchvision"
        ],
        "tasks": [
          "image_classification"
        ]
      },
      {
        "aliases": [],
        "attributes": {},
        "available": true,
        "equivalent_to": [],
        "id": "regnet",
        "implies": [],
        "runners": [
          "local_simulator",
          "modal_torchvision"
        ],
        "tasks": [
          "image_classification"
        ]
      },
      {
        "aliases": [],
        "attributes": {},
        "available": true,
        "equivalent_to": [],
        "id": "resnet",
        "implies": [],
        "runners": [
          "local_simulator",
          "modal_torchvision"
        ],
        "tasks": [
          "image_classification"
        ]
      },
      {
        "aliases": [],
        "attributes": {},
        "available": true,
        "equivalent_to": [],
        "id": "convnext",
        "implies": [],
        "runners": [
          "local_simulator",
          "modal_torchvision"
        ],
        "tasks": [
          "image_classification"
        ]
      },
      {
        "aliases": [],
        "attributes": {},
        "available": true,
        "equivalent_to": [],
        "id": "swin",
        "implies": [],
        "runners": [
          "local_simulator",
          "modal_torchvision"
        ],
        "tasks": [
          "image_classification"
        ]
      },
      {
        "aliases": [],
        "attributes": {},
        "available": true,
        "equivalent_to": [],
        "id": "vit",
        "implies": [],
        "runners": [
          "local_simulator",
          "modal_torchvision"
        ],
        "tasks": [
          "image_classification"
        ]
      },
      {
        "aliases": [],
        "attributes": {},
        "available": true,
        "equivalent_to": [],
        "id": "yolo11",
        "implies": [],
        "runners": [
          "local_simulator",
          "modal_ultralytics"
        ],
        "tasks": [
          "object_detection"
        ]
      }
    ],
    "model_size_tiers": [
      {
        "aliases": [],
        "attributes": {},
        "available": false,
        "equivalent_to": [],
        "id": "compact",
        "implies": [],
        "runners": [],
        "tasks": []
      },
      {
        "aliases": [],
        "attributes": {},
        "available": false,
        "equivalent_to": [],
        "id": "standard",
        "implies": [],
        "runners": [],
        "tasks": []
      },
      {
        "aliases": [],
        "attributes": {},
        "available": false,
        "equivalent_to": [],
        "id": "large",
        "implies": [],
        "runners": [],
        "tasks": []
      }
    ],
    "models": [
      {
        "aliases": [],
        "attributes": {
          "default_image_size": 224,
          "deployment_tier": "fast_live",
          "family": "mobilenet",
          "fine_tuning_modes": [
            "head_only",
            "last_block",
            "full"
          ],
          "latency_tier": "very_fast",
          "min_recommended_images": 50,
          "model_kind": "torchvision_classifier",
          "recommended_use": "fast live baseline and compact champion refinement",
          "supports_transfer": true,
          "training_enabled": true
        },
        "available": true,
        "equivalent_to": [],
        "id": "mobilenet_v3_small",
        "implies": [
          "model_families/mobilenet",
          "deployment_tiers/fast_live",
          "latency_tiers/very_fast"
        ],
        "runners": [
          "local_simulator",
          "modal_torchvision"
        ],
        "tasks": [
          "image_classification"
        ]
      },
      {
        "aliases": [],
        "attributes": {
          "default_image_size": 224,
          "deployment_tier": "fast_live",
          "family": "mobilenet",
          "fine_tuning_modes": [
            "head_only",
            "last_block",
            "full"
          ],
          "latency_tier": "fast",
          "min_recommended_images": 80,
          "model_kind": "torchvision_classifier",
          "recommended_use": "higher-capacity MobileNet challenger for live use",
          "supports_transfer": true,
          "training_enabled": true
        },
        "available": true,
        "equivalent_to": [],
        "id": "mobilenet_v3_large",
        "implies": [
          "model_families/mobilenet",
          "deployment_tiers/fast_live",
          "latency_tiers/fast"
        ],
        "runners": [
          "local_simulator",
          "modal_torchvision"
        ],
        "tasks": [
          "image_classification"
        ]
      },
      {
        "aliases": [],
        "attributes": {
          "default_image_size": 224,
          "deployment_tier": "fast_live",
          "family": "efficientnet",
          "fine_tuning_modes": [
            "head_only",
            "last_block",
            "full"
          ],
          "latency_tier": "fast",
          "min_recommended_images": 80,
          "model_kind": "torchvision_classifier",
          "recommended_use": "strong quality/latency baseline",
          "supports_transfer": true,
          "training_enabled": true
        },
        "available": true,
        "equivalent_to": [],
        "id": "efficientnet_b0",
        "implies": [
          "model_families/efficientnet",
          "deployment_tiers/fast_live",
          "latency_tiers/fast"
        ],
        "runners": [
          "local_simulator",
          "modal_torchvision"
        ],
        "tasks": [
          "image_classification"
        ]
      },
      {
        "aliases": [],
        "attributes": {
          "default_image_size": 224,
          "deployment_tier": "fast_live",
          "family": "regnet",
          "fine_tuning_modes": [
            "head_only",
            "last_block",
            "full"
          ],
          "latency_tier": "fast",
          "min_recommended_images": 100,
          "model_kind": "torchvision_classifier",
          "recommended_use": "compact architecture challenger",
          "supports_transfer": true,
          "training_enabled": true
        },
        "available": true,
        "equivalent_to": [],
        "id": "regnet_y_400mf",
        "implies": [
          "model_families/regnet",
          "deployment_tiers/fast_live",
          "latency_tiers/fast"
        ],
        "runners": [
          "local_simulator",
          "modal_torchvision"
        ],
        "tasks": [
          "image_classification"
        ]
      },
      {
        "aliases": [],
        "attributes": {
          "default_image_size": 240,
          "deployment_tier": "balanced",
          "family": "efficientnet",
          "fine_tuning_modes": [
            "head_only",
            "last_block",
            "full"
          ],
          "latency_tier": "medium",
          "min_recommended_images": 150,
          "model_kind": "torchvision_classifier",
          "recommended_use": "balanced quality challenger",
          "supports_transfer": true,
          "training_enabled": true
        },
        "available": true,
        "equivalent_to": [],
        "id": "efficientnet_b1",
        "implies": [
          "model_families/efficientnet",
          "deployment_tiers/balanced",
          "latency_tiers/medium"
        ],
        "runners": [
          "local_simulator",
          "modal_torchvision"
        ],
        "tasks": [
          "image_classification"
        ]
      },
      {
        "aliases": [],
        "attributes": {
          "default_image_size": 260,
          "deployment_tier": "balanced",
          "family": "efficientnet",
          "fine_tuning_modes": [
            "head_only",
            "last_block",
            "full"
          ],
          "latency_tier": "medium",
          "min_recommended_images": 250,
          "model_kind": "torchvision_classifier",
          "recommended_use": "stronger quality challenger when budget allows",
          "supports_transfer": true,
          "training_enabled": true
        },
        "available": true,
        "equivalent_to": [],
        "id": "efficientnet_b2",
        "implies": [
          "model_families/efficientnet",
          "deployment_tiers/balanced",
          "latency_tiers/medium"
        ],
        "runners": [
          "local_simulator",
          "modal_torchvision"
        ],
        "tasks": [
          "image_classification"
        ]
      },
      {
        "aliases": [],
        "attributes": {
          "default_image_size": 224,
          "deployment_tier": "balanced",
          "family": "resnet",
          "fine_tuning_modes": [
            "head_only",
            "last_block",
            "full"
          ],
          "latency_tier": "medium",
          "min_recommended_images": 100,
          "model_kind": "torchvision_classifier",
          "recommended_use": "stable control architecture",
          "supports_transfer": true,
          "training_enabled": true
        },
        "available": true,
        "equivalent_to": [],
        "id": "resnet18",
        "implies": [
          "model_families/resnet",
          "deployment_tiers/balanced",
          "latency_tiers/medium"
        ],
        "runners": [
          "local_simulator",
          "modal_torchvision"
        ],
        "tasks": [
          "image_classification"
        ]
      },
      {
        "aliases": [],
        "attributes": {
          "default_image_size": 224,
          "deployment_tier": "balanced",
          "family": "resnet",
          "fine_tuning_modes": [
            "head_only",
            "last_block",
            "full"
          ],
          "latency_tier": "medium_slow",
          "min_recommended_images": 150,
          "model_kind": "torchvision_classifier",
          "recommended_use": "larger ResNet comparison",
          "supports_transfer": true,
          "training_enabled": true
        },
        "available": true,
        "equivalent_to": [],
        "id": "resnet34",
        "implies": [
          "model_families/resnet",
          "deployment_tiers/balanced",
          "latency_tiers/medium_slow"
        ],
        "runners": [
          "local_simulator",
          "modal_torchvision"
        ],
        "tasks": [
          "image_classification"
        ]
      },
      {
        "aliases": [],
        "attributes": {
          "default_image_size": 224,
          "deployment_tier": "quality_challenger",
          "family": "convnext",
          "fine_tuning_modes": [
            "head_only",
            "last_block",
            "full"
          ],
          "latency_tier": "slow",
          "min_recommended_images": 300,
          "model_kind": "torchvision_classifier",
          "recommended_use": "quality-first challenger",
          "supports_transfer": true,
          "training_enabled": true
        },
        "available": true,
        "equivalent_to": [],
        "id": "convnext_tiny",
        "implies": [
          "model_families/convnext",
          "deployment_tiers/quality_challenger",
          "latency_tiers/slow"
        ],
        "runners": [
          "local_simulator",
          "modal_torchvision"
        ],
        "tasks": [
          "image_classification"
        ]
      },
      {
        "aliases": [],
        "attributes": {
          "default_image_size": 224,
          "deployment_tier": "quality_challenger",
          "family": "swin",
          "fine_tuning_modes": [
            "head_only",
            "last_block",
            "full"
          ],
          "latency_tier": "slow",
          "min_recommended_images": 500,
          "model_kind": "torchvision_classifier",
          "recommended_use": "transformer challenger for larger datasets",
          "supports_transfer": true,
          "training_enabled": true
        },
        "available": true,
        "equivalent_to": [],
        "id": "swin_t",
        "implies": [
          "model_families/swin",
          "deployment_tiers/quality_challenger",
          "latency_tiers/slow"
        ],
        "runners": [
          "local_simulator",
          "modal_torchvision"
        ],
        "tasks": [
          "image_classification"
        ]
      },
      {
        "aliases": [],
        "attributes": {
          "default_image_size": 224,
          "deployment_tier": "quality_challenger",
          "family": "vit",
          "fine_tuning_modes": [
            "head_only",
            "last_block",
            "full"
          ],
          "latency_tier": "slowest",
          "min_recommended_images": 800,
          "model_kind": "torchvision_classifier",
          "recommended_use": "explicit quality-first experiments on larger datasets",
          "supports_transfer": true,
          "training_enabled": true
        },
        "available": true,
        "equivalent_to": [],
        "id": "vit_b_16",
        "implies": [
          "model_families/vit",
          "deployment_tiers/quality_challenger",
          "latency_tiers/slowest"
        ],
        "runners": [
          "local_simulator",
          "modal_torchvision"
        ],
        "tasks": [
          "image_classification"
        ]
      },
      {
        "aliases": [],
        "attributes": {
          "default_image_size": 640,
          "deployment_tier": "realtime_detector",
          "family": "yolo11",
          "fine_tuning_modes": [],
          "latency_tier": "very_fast",
          "min_recommended_images": 100,
          "model_kind": "ultralytics_yolo_detector",
          "pretrained_weights": "yolo11n.pt",
          "recommended_use": "nano COCO-pretrained detector for the first live-stream baseline; schedule only for YOLO object-detection datasets.",
          "supports_transfer": true,
          "training_enabled": true
        },
        "available": true,
        "equivalent_to": [],
        "id": "yolo11n.pt",
        "implies": [
          "model_families/yolo11",
          "deployment_tiers/realtime_detector",
          "latency_tiers/very_fast"
        ],
        "runners": [
          "local_simulator",
          "modal_ultralytics"
        ],
        "tasks": [
          "object_detection"
        ]
      },
      {
        "aliases": [],
        "attributes": {
          "default_image_size": 640,
          "deployment_tier": "realtime_detector",
          "family": "yolo11",
          "fine_tuning_modes": [],
          "latency_tier": "fast",
          "min_recommended_images": 100,
          "model_kind": "ultralytics_yolo_detector",
          "pretrained_weights": "yolo11s.pt",
          "recommended_use": "small COCO-pretrained detector with stronger accuracy while staying live-friendly; schedule only for YOLO object-detection datasets.",
          "supports_transfer": true,
          "training_enabled": true
        },
        "available": true,
        "equivalent_to": [],
        "id": "yolo11s.pt",
        "implies": [
          "model_families/yolo11",
          "deployment_tiers/realtime_detector",
          "latency_tiers/fast"
        ],
        "runners": [
          "local_simulator",
          "modal_ultralytics"
        ],
        "tasks": [
          "object_detection"
        ]
      },
      {
        "aliases": [],
        "attributes": {
          "default_image_size": 640,
          "deployment_tier": "quality_detector",
          "family": "yolo11",
          "fine_tuning_modes": [],
          "latency_tier": "medium",
          "min_recommended_images": 100,
          "model_kind": "ultralytics_yolo_detector",
          "pretrained_weights": "yolo11m.pt",
          "recommended_use": "medium COCO-pretrained detector for quality challengers when latency budget allows; schedule only for YOLO object-detection datasets.",
          "supports_transfer": true,
          "training_enabled": true
        },
        "available": true,
        "equivalent_to": [],
        "id": "yolo11m.pt",
        "implies": [
          "model_families/yolo11",
          "deployment_tiers/quality_detector",
          "latency_tiers/medium"
        ],
        "runners": [
          "local_simulator",
          "modal_ultralytics"
        ],
        "tasks": [
          "object_detection"
        ]
      },
      {
        "aliases": [],
        "attributes": {
          "default_image_size": 640,
          "deployment_tier": "quality_detector",
          "family": "yolo11",
          "fine_tuning_modes": [],
          "latency_tier": "slow",
          "min_recommended_images": 100,
          "model_kind": "ultralytics_yolo_detector",
          "pretrained_weights": "yolo11l.pt",
          "recommended_use": "large COCO-pretrained detector for high-accuracy offline comparison; schedule only for YOLO object-detection datasets.",
          "supports_transfer": true,
          "training_enabled": true
        },
        "available": true,
        "equivalent_to": [],
        "id": "yolo11l.pt",
        "implies": [
          "model_families/yolo11",
          "deployment_tiers/quality_detector",
          "latency_tiers/slow"
        ],
        "runners": [
          "local_simulator",
          "modal_ultralytics"
        ],
        "tasks": [
          "object_detection"
        ]
      },
      {
        "aliases": [],
        "attributes": {
          "default_image_size": 640,
          "deployment_tier": "quality_detector",
          "family": "yolo11",
          "fine_tuning_modes": [],
          "latency_tier": "slowest",
          "min_recommended_images": 100,
          "model_kind": "ultralytics_yolo_detector",
          "pretrained_weights": "yolo11x.pt",
          "recommended_use": "extra-large COCO-pretrained detector for upper-bound detection quality studies; schedule only for YOLO object-detection datasets.",
          "supports_transfer": true,
          "training_enabled": true
        },
        "available": true,
        "equivalent_to": [],
        "id": "yolo11x.pt",
        "implies": [
          "model_families/yolo11",
          "deployment_tiers/quality_detector",
          "latency_tiers/slowest"
        ],
        "runners": [
          "local_simulator",
          "modal_ultralytics"
        ],
        "tasks": [
          "object_detection"
        ]
      }
    ],
    "normalization_strategies": [
      {
        "aliases": [],
        "attributes": {},
        "available": true,
        "equivalent_to": [],
        "id": "imagenet",
        "implies": [],
        "runners": [
          "local_simulator",
          "modal_torchvision"
        ],
        "tasks": [
          "image_classification"
        ]
      },
      {
        "aliases": [],
        "attributes": {},
        "available": true,
        "equivalent_to": [],
        "id": "dataset",
        "implies": [],
        "runners": [
          "local_simulator",
          "modal_torchvision"
        ],
        "tasks": [
          "image_classification"
        ]
      },
      {
        "aliases": [],
        "attributes": {},
        "available": true,
        "equivalent_to": [],
        "id": "none",
        "implies": [],
        "runners": [
          "local_simulator",
          "modal_torchvision"
        ],
        "tasks": [
          "image_classification"
        ]
      }
    ],
    "optimizers": [
      {
        "aliases": [],
        "attributes": {},
        "available": true,
        "equivalent_to": [],
        "id": "adamw",
        "implies": [],
        "runners": [
          "local_simulator",
          "modal_torchvision"
        ],
        "tasks": [
          "image_classification"
        ]
      },
      {
        "aliases": [],
        "attributes": {},
        "available": true,
        "equivalent_to": [],
        "id": "adam",
        "implies": [],
        "runners": [
          "local_simulator",
          "modal_torchvision"
        ],
        "tasks": [
          "image_classification"
        ]
      },
      {
        "aliases": [],
        "attributes": {},
        "available": true,
        "equivalent_to": [],
        "id": "sgd",
        "implies": [],
        "runners": [
          "local_simulator",
          "modal_torchvision"
        ],
        "tasks": [
          "image_classification"
        ]
      }
    ],
    "precisions": [
      {
        "aliases": [],
        "attributes": {},
        "available": true,
        "equivalent_to": [],
        "id": "fp32",
        "implies": [],
        "runners": [
          "modal_torchvision",
          "modal_ultralytics"
        ],
        "tasks": [
          "image_classification",
          "object_detection"
        ]
      },
      {
        "aliases": [],
        "attributes": {},
        "available": false,
        "equivalent_to": [],
        "id": "fp16",
        "implies": [],
        "runners": [],
        "tasks": []
      },
      {
        "aliases": [],
        "attributes": {},
        "available": false,
        "equivalent_to": [],
        "id": "int8",
        "implies": [],
        "runners": [],
        "tasks": []
      }
    ],
    "resize_strategies": [
      {
        "aliases": [],
        "attributes": {},
        "available": true,
        "equivalent_to": [],
        "id": "squash",
        "implies": [],
        "runners": [
          "local_simulator",
          "modal_torchvision"
        ],
        "tasks": [
          "image_classification",
          "object_detection"
        ]
      },
      {
        "aliases": [],
        "attributes": {},
        "available": true,
        "equivalent_to": [],
        "id": "preserve_aspect_pad",
        "implies": [],
        "runners": [
          "modal_torchvision"
        ],
        "tasks": [
          "image_classification"
        ]
      },
      {
        "aliases": [],
        "attributes": {},
        "available": true,
        "equivalent_to": [],
        "id": "center_crop",
        "implies": [],
        "runners": [
          "local_simulator",
          "modal_torchvision"
        ],
        "tasks": [
          "image_classification"
        ]
      },
      {
        "aliases": [],
        "attributes": {},
        "available": true,
        "equivalent_to": [],
        "id": "random_resized_crop",
        "implies": [],
        "runners": [
          "local_simulator",
          "modal_torchvision"
        ],
        "tasks": [
          "image_classification"
        ]
      },
      {
        "aliases": [],
        "attributes": {},
        "available": true,
        "equivalent_to": [],
        "id": "bbox_crop_if_available",
        "implies": [],
        "runners": [
          "modal_torchvision"
        ],
        "tasks": [
          "image_classification"
        ]
      },
      {
        "aliases": [
          "letterbox"
        ],
        "attributes": {},
        "available": true,
        "equivalent_to": [],
        "id": "yolo_letterbox",
        "implies": [],
        "runners": [
          "modal_ultralytics"
        ],
        "tasks": [
          "object_detection"
        ]
      }
    ],
    "resolution_strategies": [
      {
        "aliases": [],
        "attributes": {},
        "available": true,
        "equivalent_to": [],
        "id": "fixed",
        "implies": [],
        "runners": [
          "local_simulator",
          "modal_torchvision"
        ],
        "tasks": [
          "image_classification"
        ]
      },
      {
        "aliases": [],
        "attributes": {},
        "available": true,
        "equivalent_to": [],
        "id": "low_latency",
        "implies": [],
        "runners": [
          "local_simulator",
          "modal_torchvision"
        ],
        "tasks": [
          "image_classification"
        ]
      },
      {
        "aliases": [],
        "attributes": {},
        "available": true,
        "equivalent_to": [],
        "id": "compare_224_256",
        "implies": [],
        "runners": [
          "local_simulator",
          "modal_torchvision"
        ],
        "tasks": [
          "image_classification"
        ]
      },
      {
        "aliases": [],
        "attributes": {},
        "available": true,
        "equivalent_to": [],
        "id": "high_resolution_ablation",
        "implies": [],
        "runners": [
          "local_simulator",
          "modal_torchvision"
        ],
        "tasks": [
          "image_classification"
        ]
      }
    ],
    "runners": [
      {
        "aliases": [],
        "attributes": {
          "simulated": true
        },
        "available": true,
        "equivalent_to": [],
        "id": "local_simulator",
        "implies": [],
        "runners": [
          "local_simulator"
        ],
        "tasks": [
          "image_classification",
          "object_detection"
        ]
      },
      {
        "aliases": [],
        "attributes": {
          "model_kind": "torchvision_classifier",
          "simulated": false
        },
        "available": true,
        "equivalent_to": [],
        "id": "modal_torchvision",
        "implies": [],
        "runners": [
          "modal_torchvision"
        ],
        "tasks": [
          "image_classification"
        ]
      },
      {
        "aliases": [],
        "attributes": {
          "model_kind": "ultralytics_yolo_detector",
          "simulated": false
        },
        "available": true,
        "equivalent_to": [],
        "id": "modal_ultralytics",
        "implies": [],
        "runners": [
          "modal_ultralytics"
        ],
        "tasks": [
          "object_detection"
        ]
      }
    ],
    "runtimes": [
      {
        "aliases": [
          "onnx_runtime"
        ],
        "attributes": {},
        "available": true,
        "equivalent_to": [],
        "id": "onnxruntime",
        "implies": [],
        "runners": [
          "modal_torchvision",
          "modal_ultralytics"
        ],
        "tasks": [
          "image_classification",
          "object_detection"
        ]
      },
      {
        "aliases": [],
        "attributes": {},
        "available": true,
        "equivalent_to": [],
        "id": "torchscript",
        "implies": [],
        "runners": [
          "modal_torchvision"
        ],
        "tasks": [
          "image_classification"
        ]
      },
      {
        "aliases": [],
        "attributes": {},
        "available": true,
        "equivalent_to": [],
        "id": "pytorch",
        "implies": [],
        "runners": [
          "modal_torchvision",
          "modal_ultralytics"
        ],
        "tasks": [
          "image_classification",
          "object_detection"
        ]
      }
    ],
    "sampling_strategies": [
      {
        "aliases": [],
        "attributes": {},
        "available": true,
        "equivalent_to": [],
        "id": "none",
        "implies": [],
        "runners": [
          "local_simulator",
          "modal_torchvision"
        ],
        "tasks": [
          "image_classification"
        ]
      },
      {
        "aliases": [],
        "attributes": {},
        "available": true,
        "equivalent_to": [],
        "id": "class_balanced_sampler",
        "implies": [],
        "runners": [
          "local_simulator",
          "modal_torchvision"
        ],
        "tasks": [
          "image_classification"
        ]
      },
      {
        "aliases": [],
        "attributes": {},
        "available": true,
        "equivalent_to": [],
        "id": "weighted_random_sampler",
        "implies": [],
        "runners": [
          "local_simulator",
          "modal_torchvision"
        ],
        "tasks": [
          "image_classification"
        ]
      }
    ],
    "schedulers": [
      {
        "aliases": [],
        "attributes": {},
        "available": true,
        "equivalent_to": [],
        "id": "none",
        "implies": [],
        "runners": [
          "local_simulator",
          "modal_torchvision"
        ],
        "tasks": [
          "image_classification"
        ]
      },
      {
        "aliases": [],
        "attributes": {},
        "available": true,
        "equivalent_to": [],
        "id": "cosine",
        "implies": [],
        "runners": [
          "local_simulator",
          "modal_torchvision"
        ],
        "tasks": [
          "image_classification"
        ]
      },
      {
        "aliases": [],
        "attributes": {},
        "available": true,
        "equivalent_to": [],
        "id": "step",
        "implies": [],
        "runners": [
          "local_simulator",
          "modal_torchvision"
        ],
        "tasks": [
          "image_classification"
        ]
      }
    ],
    "tasks": [
      {
        "aliases": [],
        "attributes": {},
        "available": true,
        "equivalent_to": [],
        "id": "image_classification",
        "implies": [],
        "runners": [
          "local_simulator",
          "modal_torchvision"
        ],
        "tasks": [
          "image_classification"
        ]
      },
      {
        "aliases": [],
        "attributes": {},
        "available": true,
        "equivalent_to": [],
        "id": "object_detection",
        "implies": [],
        "runners": [
          "local_simulator",
          "modal_ultralytics"
        ],
        "tasks": [
          "object_detection"
        ]
      }
    ]
  },
  "schema_version": "model_express_catalog.v1"
}
''')
CATALOG_VERSION = str(CATALOG_DOCUMENT["catalog_version"])
SCHEMA_VERSION = str(CATALOG_DOCUMENT["schema_version"])
CATALOG_IDS = {
    category: frozenset(entry["id"] for entry in entries)
    for category, entries in CATALOG_DOCUMENT["categories"].items()
}
CATALOG_ALIASES = {
    category: {alias: entry["id"] for entry in entries for alias in entry["aliases"]}
    for category, entries in CATALOG_DOCUMENT["categories"].items()
}
