#!/usr/bin/env python3
"""Validate immutable compatibility profiles and generate server/UI/migration bindings."""

from __future__ import annotations

import argparse
import hashlib
import json
from pathlib import Path
from typing import Any


ROOT = Path(__file__).resolve().parents[1]
PROFILE_DIR = ROOT / "contracts" / "compatibility_profiles"
CATALOG_PATH = ROOT / "contracts" / "model_express_catalog.v1.json"
GO_PATH = ROOT / "services" / "orchestrator" / "internal" / "policies" / "compatibility_profiles_generated.go"
TS_PATH = ROOT / "apps" / "mission-control" / "src" / "compatibilityProfiles.generated.ts"
SQL_PATH = ROOT / "services" / "orchestrator" / "internal" / "store" / "migrations" / "026_roasty_v1.sql"


def canonical(value: Any) -> str:
    return json.dumps(value, ensure_ascii=False, separators=(",", ":"), sort_keys=True)


def load_profiles() -> list[dict[str, Any]]:
    catalog = json.loads(CATALOG_PATH.read_text(encoding="utf-8"))
    categories = catalog["categories"]
    known = {name: {entry["id"]: entry for entry in entries} for name, entries in categories.items()}
    profiles: list[dict[str, Any]] = []
    identities: set[str] = set()
    for path in sorted(PROFILE_DIR.glob("*.json")):
        profile = json.loads(path.read_text(encoding="utf-8"))
        if set(profile) != {"profile_key", "semantic_version", "document"}:
            raise ValueError(f"{path.name}: invalid profile envelope")
        identity = f'{profile["profile_key"]}@{profile["semantic_version"]}'
        if identity in identities:
            raise ValueError(f"duplicate profile {identity}")
        identities.add(identity)
        document = profile["document"]
        if document.get("schema_version") != "model_express_compatibility_profile.v1":
            raise ValueError(f"{identity}: invalid schema version")
        if document.get("catalog_version") != catalog["catalog_version"]:
            raise ValueError(f"{identity}: stale catalog version")
        seen_rules: set[str] = set()
        normalized_rules: list[dict[str, Any]] = []
        for rule in document.get("rules", []):
            rule_id = str(rule.get("id", "")).strip()
            selector = rule.get("selector", {})
            category = selector.get("catalog")
            ids = selector.get("ids")
            if not rule_id or rule_id in seen_rules or rule.get("effect") != "allow":
                raise ValueError(f"{identity}: invalid or duplicate allow rule {rule_id!r}")
            if selector.get("kind") != "catalog_ids" or category not in known or not isinstance(ids, list) or not ids:
                raise ValueError(f"{identity}: rule {rule_id} must select catalog IDs")
            unknown = set(ids) - set(known[category])
            unavailable = {value for value in ids if not known[category][value]["available"]}
            if unknown or unavailable:
                raise ValueError(f"{identity}: invalid {category} IDs unknown={sorted(unknown)} unavailable={sorted(unavailable)}")
            seen_rules.add(rule_id)
            normalized_rules.append({"id": rule_id, "effect": "allow", "selector": {"kind": "catalog_ids", "catalog": category, "ids": sorted(set(ids))}})
        if not normalized_rules:
            raise ValueError(f"{identity}: profile has no rules")
        profile["document"] = {
            "schema_version": document["schema_version"],
            "catalog_version": document["catalog_version"],
            "rules": sorted(normalized_rules, key=lambda item: item["id"]),
            "metadata": {
                "display_name": str(document.get("metadata", {}).get("display_name", "")).strip(),
                "description": str(document.get("metadata", {}).get("description", "")).strip(),
            },
        }
        profiles.append(profile)

    roasty = next((item for item in profiles if item["profile_key"] == "roasty_v1" and item["semantic_version"] == "1.0.0"), None)
    if roasty is None:
        raise ValueError("roasty_v1@1.0.0 is required")
    selected = {rule["selector"]["catalog"]: rule["selector"]["ids"] for rule in roasty["document"]["rules"]}
    required = {
        "tasks": ["image_classification"], "runners": ["modal_torchvision"],
        "export_formats": ["onnx"], "precisions": ["fp32"], "runtimes": ["onnxruntime"],
        "execution_providers": ["cpu_execution_provider"], "execution_requirements": ["cpu_compatible"],
    }
    for category, expected in required.items():
        if selected.get(category) != expected:
            raise ValueError(f"roasty_v1 must contain only {category}={expected}")
    return profiles


def render_go(profiles: list[dict[str, Any]]) -> str:
    source = canonical(profiles)
    digest = hashlib.sha256(source.encode()).hexdigest()
    return f'''// Code generated by generate_compatibility_profiles.py; DO NOT EDIT.
// Source SHA-256: {digest}

package policies

const generatedCompatibilityProfilesJSON = `{source}`
'''


def render_ts(profiles: list[dict[str, Any]]) -> str:
    source = json.dumps(profiles, ensure_ascii=False, indent=2, sort_keys=True)
    digest = hashlib.sha256(canonical(profiles).encode()).hexdigest()
    return f'''// Code generated by generate_compatibility_profiles.py; DO NOT EDIT.
// Source SHA-256: {digest}

export const COMPATIBILITY_PROFILES = JSON.parse(String.raw`{source}`) as readonly {{
  profile_key: string;
  semantic_version: string;
  document: {{ metadata: {{ display_name: string; description: string }}; rules: readonly unknown[] }};
}}[];
'''


def render_sql(profiles: list[dict[str, Any]]) -> str:
    rows: list[str] = ["-- Code generated by generate_compatibility_profiles.py; DO NOT EDIT."]
    for profile in profiles:
        document = profile["document"]
        document_json = canonical(document).replace("'", "''")
        document_hash = "sha256:" + hashlib.sha256(canonical(document).encode()).hexdigest()
        rows.append(f'''INSERT INTO compatibility_profiles (
  profile_key, semantic_version, schema_version, catalog_version,
  document, document_hash, owner_account_id, created_by
)
VALUES (
  '{profile["profile_key"]}', '{profile["semantic_version"]}',
  '{document["schema_version"]}', '{document["catalog_version"]}',
  '{document_json}'::jsonb, '{document_hash}', NULL, 'builtin_generator'
)
ON CONFLICT (profile_key, semantic_version) DO NOTHING;''')
    return "\n\n".join(rows) + "\n"


def write_or_check(path: Path, expected: str, check: bool) -> bool:
    if check:
        if not path.exists() or path.read_text(encoding="utf-8") != expected:
            print(f"stale generated artifact: {path.relative_to(ROOT)}")
            return False
        return True
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(expected, encoding="utf-8")
    print(f"generated {path.relative_to(ROOT)}")
    return True


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    profiles = load_profiles()
    outputs = [(GO_PATH, render_go(profiles)), (TS_PATH, render_ts(profiles)), (SQL_PATH, render_sql(profiles))]
    return 0 if all(write_or_check(path, content, args.check) for path, content in outputs) else 1


if __name__ == "__main__":
    raise SystemExit(main())
